### ISSUE TITLE
control the zoom step

### ISSUE THREAD

**Issue by mdsumner** [alexgleith/tasmap.org#1]
I wonder if we could get finer grained control on zoom? Mouse roll and the buttons +/- are a bit too big in step.   

I'll have an explore myself at some point, cheers!

**Comment by alexgleith** [comment]
Thanks, @mdsumner.

It's probably time to update the Leaflet version for this app. We can add 'fractional zoom' then ;-).

I'll see if I can find to do it.

**Comment by alexgleith** [comment]
Hey @mdsumner, I changed it a bit by including 0.5 zoom levels.

There's no option for smooth zooming, though. I think you need MapboxGL to do that...

**Comment by mdsumner** [comment]
Hey that's great, thanks!  

It's time I got into this, and MapboxGL ...
